### ISSUE TITLE
Bug in Transfer.add_links?

### ISSUE THREAD

**Issue by fservantwiremind** [astrikos/wetransfer-python-sdk#3]
Hello,
Using wetransfer-0.0.1, in the implementation of `Transfer.add_links` it is written:
```python
self.transfer_items.append(File(url))
```
I guess you would have wanted to write
```python
self.transfer_items.append(Link(url))
```
instead?

**Comment by astrikos** [comment]
🤦‍♂️ you are right ofcourse! The lack of tests has already started to become obvious. Feel free to submit a PR with the fix, otherwise I am going to fix it later today.

**Comment by astrikos** [comment]
Addressed in https://github.com/astrikos/wetransfer-python-sdk/commit/5b961e48d175c66be040eb1f8e4bf1d1e80c6f11.
Closing now thanks for the report!
